spring:
    datasource:
        password: password
        url: jdbc:postgresql://localhost:5432/auth_db4
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
                        
        show_sql: true                
    liquibase:
              
              change-log: classpath:liquibase/master.xml
    
logging:
  file.name: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.mids.auth.role: DEBUG
    org.hibernate: ERROR
server:
  port: 8102
                